POST http://localhost:1807/followers HTTP/1.1
Content-Type: application/json

{
    "userId": "820f630c-d9ae-44c0-86a9-81c3cc9d2ccc",
    "followerId": "2be433b6-e24a-4597-ab8f-855cbd71847f"
}
###
GET http://localhost:1807/followers?userId=820f630c-d9ae-44c0-86a9-81c3cc9d2ccc HTTP/1.1
###
GET http://localhost:1807/followers/313fca44-be66-42d2-9ee7-dffc7dedefc2 HTTP/1.1
###
DELETE http://localhost:1807/followers/313fca44-be66-42d2-9ee7-dffc7dedefc2 HTTP/1.1