POST http://localhost:1807/replies HTTP/1.1
Content-Type: application/json

{
    "content": "Caraca, que legal, espero que você consiga uma boa nota, com este trabalho 😊",
    "type": "Reply",
    "userId": "efc911f1-237c-4edf-8cd1-3258e5abb85f",
    "tweetId": "b95c3d22-c5df-45c1-8850-c6ab68a410c6"
}
###
GET http://localhost:1807/replies?type=Reply HTTP/1.1
###
GET http://localhost:1807/replies/022e2a77-9300-4ecb-96a7-cbdd09ecf8ac HTTP/1.1
###
PUT http://localhost:1807/replies/022e2a77-9300-4ecb-96a7-cbdd09ecf8ac HTTP/1.1
Content-Type: application/json

{
    "content": "Parabéns, você é 10 !!!"
}

###
DELETE http://localhost:1807/replies/022e2a77-9300-4ecb-96a7-cbdd09ecf8ac HTTP/1.1

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 261
etag: W/"105-goNdf2yfoGTkFbmm4Q1WyfurwEI"
date: Sun, 03 Nov 2024 20:27:40 GMT
connection: close